### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [wegoedod/PY202309#2]
### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week7/todo
    - invalid syntax (<unknown>, line 7)
        - 파이썬에서 주석은 # 로 작성해주세요. // 로 작성하여 파일이 제대로 실행되지 않습니다. 

## 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/list_and_tuple
    - 55:Undefined variable 'yesterday_salese'	total_sales = yesterday_salese+today_sales
    - 56:Undefined variable 'yesterday_salese'	print("Yesterday sales:",yesterday_salese)
        - yesterday_salese 변수가 없습니다. 오타를 수정해주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week7/todo

**Comment by wegoedod** [comment]
#2 week3 list_and_tuple에서 오타 수정했고 week7 todo에서 주석 기호를 #으로 변경했습니다.
